### ISSUE TITLE
Cannot Autoscale VM's

### ISSUE THREAD

**Issue by lauxtermann-aram** [wbuchwalter/Kubernetes-acs-engine-autoscaler#69]
Hi,

I deployed the ACS-Engine autoscaler with a values.yml and helm.

**values.yml**
```
acsenginecluster:
  resourcegroup: XXX
  azurespappid: XXX-XXX-XXX
  azurespsecret: XXX
  azuresptenantid: XXX-XXX-XXX
  kubeconfigprivatekey: XXX
  clientprivatekey: XXX
  caprivatekey: XXX
```
**cmd:** helm install stable/acs-engine-autoscaler -f values.yml

I also tried to installing with a helm upgrade.

**cmd:** 
```
helm upgrade yodeling-elk \
    --set acsenginecluster.resourcegroup=
```
Containing all acsenginecluster.<VALUES>, but I keep getting the following **Error**:

> 2017-12-06 10:48:32,870 - autoscaler.cluster - DEBUG - Using kube service account
> 2017-12-06 10:48:32,871 - autoscaler.cluster - INFO - ++++ Running Scaling Loop ++++++
> 2017-12-06 10:48:32,899 - autoscaler.cluster - WARNING - Unexpected error: &lt;class 'KeyError'&gt;

Does anyone (William?) know how to resolve this error? 

Thank you!
