### ISSUE TITLE
Unexpected error: <class 'requests.exceptions.HTTPError'>

### ISSUE THREAD

**Issue by markwragg** [wbuchwalter/Kubernetes-acs-engine-autoscaler#89]
I am trying to use Helm to provision the autoscaler. The container starts, but repeatedly returns:
```
autoscaler.cluster - WARNING - Unexpected error: <class 'requests.exceptions.HTTPError'>
```
 I've read the two issues where this error was previously reported but they haven't helped unfortunately.

This is my (redacted) values.yaml:
```
replicaCount: 1
## Image for kubernetes-acs-engine-autoscaler
## Will update the image and tag later
image:
  repository: wbuchwalter/kubernetes-acs-engine-autoscaler
  tag: 2.1.1
  pullPolicy: Always
rbac:
  install: true
  apiVersion: v1beta1
acsenginecluster:
  resourcegroup: redacted
  azurespappid: redacted
  azurespsecret: redacted
  azuresptenantid: redacted
  kubeconfigprivatekey: redacted
  subscriptionid: redacted
  clientprivatekey: redacted
  caprivatekey: redacted
  acsdeployment: redacted
```
If I change tag to `latest` the container doesn't run and I get a message indicating that I didn't supply the required Azure settings. This doesn't happen with tag is 2.1.1 as above.

I've tried also adding `etcdClientPrivateKey` and `etcdServerPrivateKey` but this doesn't seem to help. Any idea what i'm doing wrong?

Many Thanks,
Mark
